Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/06/2022
Var
i:inteiro
numero: vetor [1..10] de inteiro
resultado:real
Inicio
para i de 1 ate 10 faca

escreva("Escreva um numero")
leia(numero[i])

resultado <- numero[i] / 2

escreval(resultado)
fimpara

Fimalgoritmo